import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { BookmarkProvider } from "@/context/BookmarkContext";

const outfit = Outfit({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "./globals.css";
import { ReactNode } from "react";
import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";
import SearchBar from "@/components/SearchBar";
import { Suspense } from "react";

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`bg-darkestBlue text-white ${outfit.className}`}>
        <BookmarkProvider>
          <div className="flex min-h-screen">
            <Sidebar className="hidden lg:flex" />
            <div className="flex-1 flex flex-col">
              <Topbar className="lg:hidden" />
              <main className="flex-1 px-4 md:px-6 lg:px-8 py-6">
                <Suspense>
                  <SearchBar />
                </Suspense>
                {children}
                </main>
            </div>
          </div>
        </BookmarkProvider>
      </body>
    </html>
  );
}